# Generated by Django 5.0.6 on 2024-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='user_type',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
