# Generated by Django 5.0.6 on 2024-06-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_seeker_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='user_type',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
