# Generated by Django 5.0.6 on 2024-06-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appliedjobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
    ]
