# Generated by Django 5.0.6 on 2024-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employer_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('user_type', models.CharField(default=1, max_length=255)),
            ],
        ),
    ]
