# Generated by Django 5.0.6 on 2024-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_approvedseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('user_type', models.CharField(default=1, max_length=255)),
            ],
        ),
    ]
