# Generated by Django 5.0.6 on 2024-06-10 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_approvedemployer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedemployer',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
