# Generated by Django 5.0.6 on 2024-06-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_approvedemployer_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedemployer',
            name='user_typee',
        ),
        migrations.AlterField(
            model_name='approvedemployer',
            name='user_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
