# Generated by Django 5.0.6 on 2024-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='Waiting for approval', max_length=255),
        ),
    ]
